### ISSUE TITLE
Documentation with Example

### ISSUE THREAD

**Issue by bitxplora** [Bagaar/ember-pagination#85]
Thank you for making this project available to the Emberjs community. I observed that this project would greatly benefit the community if the documentation was improved and included examples. I checked the project's test-app folder but found none. Improved documentation would make it easier for others to contribute rather than having to create something new for their use

**Comment by bertdeblock** [comment]
The usage is documented here: https://github.com/Bagaar/ember-pagination?tab=readme-ov-file#usage.

Additional examples can be found here: https://github.com/Bagaar/ember-pagination/blob/main/test-app/tests/integration/components/pagination-data-test.ts.
